server:
  port: 80

spring:
  application:
    name: student-consumer-80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2333/eureka
  instance:
    instance-id: student-consumer-80