server:
  port: 9999

spring:
  application:
    name: spring-cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2333/eureka
  instance:
    instance-id: zuul9999.com
    prefer-ip-address: true
