server:
  port: 8888

spring:
  application:
    name: config-server-8888
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yi1275432232/learn-spring-cloud-config.git
          search-paths: eureka-config*, student-producer-config*, student-consumer-config*, zuul-config*